# guard/explainer/engine.py
from guard.models import Verdict
from guard.explainer.templates import EXPLANATION_TEMPLATES
from guard.config import policy

class ExplainerEngine:
    def __init__(self):
        pass

    def explain(self, verdict: Verdict) -> str:
        if verdict.level == "ALLOW":
            return "No significant threats detected."
            
        explanations = []
        
        # 1. Use reasons generated by FusionEngine (which uses tactic classifiers)
        for reason in verdict.reasons:
            if "urgency" in reason:
                explanations.append(f"{EXPLANATION_TEMPLATES['urgency']['header']} {EXPLANATION_TEMPLATES['urgency']['detail']}")
            elif "authority" in reason:
                explanations.append(f"{EXPLANATION_TEMPLATES['authority']['header']} {EXPLANATION_TEMPLATES['authority']['detail']}")
            elif "credential" in reason:
                explanations.append(f"{EXPLANATION_TEMPLATES['credential_request']['header']} {EXPLANATION_TEMPLATES['credential_request']['detail']}")
            elif "financial" in reason:
                explanations.append(f"{EXPLANATION_TEMPLATES['financial']['header']} {EXPLANATION_TEMPLATES['financial']['detail']}")
                
        # 2. Add structural anomalies
        if verdict.component_scores.get("headers_anomaly_count", 0) > 0:
            explanations.append(f"{EXPLANATION_TEMPLATES['headers_anomaly']['header']} {EXPLANATION_TEMPLATES['headers_anomaly']['detail']}")
            
        # 3. Fallback
        if not explanations:
            explanations.append(f"{EXPLANATION_TEMPLATES['general']['header']} {EXPLANATION_TEMPLATES['general']['detail']}")
            
        # Format cleanly
        max_reasons = policy.get('explainer', {}).get('max_reasons', 5)
        formatted = "### PhishGuard Explanation\n\n"
        for idx, exp in enumerate(explanations[:max_reasons]):
            formatted += f"{idx+1}. {exp}\n"
            
        return formatted

explainer_engine = ExplainerEngine()
