from guard.models import ParsedEmail, Verdict
from guard.nlp.classifier import classifier
from guard.nlp.tactic_classifier import tactic_classifier
from guard.headers.rules import get_header_features
from guard.config import policy
import numpy as np

class FusionEngine:
    def __init__(self):
        # We would load LightGBM meta-classifier here
        self.ready = True
        
    def evaluate(self, uid: int, parsed: ParsedEmail) -> Verdict:
        # 1. Base Classifiers
        text_phish_prob = classifier.classify(parsed.normalized_body)
        tactics = tactic_classifier.classify(parsed.normalized_body)
        headers = get_header_features(parsed)
        
        # 2. Extract specific tactics for explanation
        reasons = []
        for t, prob in tactics.items():
            if prob > policy.get('explainer', {}).get('confidence_threshold', 0.6):
                reasons.append(f"High {t} confidence: {prob:.2f}")
                
        # 3. Dummy Meta-Fusion
        # In reality, this would be `meta_model.predict(features)`
        # Here we just use a heuristic based on text phish prob
        score = text_phish_prob + (0.1 if headers.sum() > 0 else 0.0)
        
        level = "ALLOW"
        if score > policy.get('thresholds', {}).get('block', 0.85):
            level = "BLOCK"
        elif score > policy.get('thresholds', {}).get('flag', 0.50):
            level = "FLAG"
            
        components = {
            "text": text_phish_prob,
            "headers_anomaly_count": float(headers.sum()),
            **tactics
        }
        
        return Verdict(
            uid=uid,
            score=score,
            level=level,
            reasons=reasons,
            component_scores=components,
            explanation=None # Generated by Explainer
        )

fusion_engine = FusionEngine()
